### PR TITLE
Change scope to be cleaner

### PR DESCRIPTION
**Pull request by Zacharias3690**
Removed double $compile
add page dropdown option

### CODE REVIEW

**Comment by Zacharias3690** [comment]
@timgit go through and make sure everything's working for you. This takes care of issue #16 as well as cleaning up our scope. If there was a function on the controller with the same name as one of ours both functions would be called.

**Comment by timgit** [comment]
shouldn't we use watchCollection instead of watch for tc-data?

**Comment by timgit** [comment]
Either that or a deep watch

**Comment by Zacharias3690** [comment]
Actually, yes, watchCollection would be way better.

**Pull request merged**
